### ISSUE TITLE
app install error

### ISSUE THREAD

**Issue by Pisard** [libracore/erpnextswiss#115]
When i do on fresh install of erpnext 13
bench --site site_name install-app erpnextswiss

I got This issue 
Installing erpnextswiss...
Updating DocTypes for erpnextswiss  : [========================================] 100%
An error occurred while installing erpnextswiss: A field with the name 'total_taxes_and_charges' already exists in doctype Expense Claim.
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 293, in install_app
    _install_app(app, verbose=context.verbose)
  File "apps/frappe/frappe/installer.py", line 199, in install_app
    sync_fixtures(name)
  File "apps/frappe/frappe/utils/fixtures.py", line 22, in sync_fixtures
    import_doc(fixtures_path)
  File "apps/frappe/frappe/core/doctype/data_import/data_import.py", line 180, in import_doc
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 146, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 275, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 256, in insert
    self.run_method("before_insert")
  File "apps/frappe/frappe/model/document.py", line 943, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 940, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 44, in before_insert
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 504, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 479, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 434, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: A field with the name 'total_taxes_and_charges' already exists in doctype Expense Claim.

### Observed in (version)
13.52.00

### Steps to reproduce
bench --site site_name install-app erpnextswiss

**Comment by lasalesi** [comment]
you need to use the compatibility branch for installations in v13
