### ISSUE TITLE
Can't install on erpnext v13.42.5

### ISSUE THREAD

**Issue by afrocubanito** [libracore/erpnextswiss#123]
### Expected behvauour
(fill in)

### Actual behaviour
(fill in)

### Observed in (version)
(fill in)

### Steps to reproduce
(fill in)

Installing erpnextswiss...
Updating DocTypes for erpnextswiss  : [========================================] 100%
An error occurred while installing erpnextswiss: A field with the name 'total_taxes_and_charges' already exists in doctype Expense Claim.
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 293, in install_app
    _install_app(app, verbose=context.verbose)
  File "apps/frappe/frappe/installer.py", line 199, in install_app
    sync_fixtures(name)
  File "apps/frappe/frappe/utils/fixtures.py", line 22, in sync_fixtures
    import_doc(fixtures_path)
  File "apps/frappe/frappe/core/doctype/data_import/data_import.py", line 180, in import_doc
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 146, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 275, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 255, in insert
    self.run_method("before_insert")
  File "apps/frappe/frappe/model/document.py", line 942, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1263, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1245, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 939, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 44, in before_insert
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 504, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 479, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 434, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: A field with the name 'total_taxes_and_charges' already exists in doctype Expense Claim.

**Comment by lasalesi** [comment]
Please use the `v13` compatibility branch, not master. ERPNext has copied this field from this repo without renaming it, creating a duplicate conflict.
