### ISSUE TITLE
Create bank transfer file fails with "Error while generating xml."

### ISSUE THREAD

**Issue by lasalesi** [libracore/erpnextswiss#18]
### Expected behvauour
Payments are compiled into a payment instruction xml file (ERPNextSwiss > Create payment file).

### Actual behaviour
The creation fails with 
![grafik](https://user-images.githubusercontent.com/26505250/40423521-237bb746-5e93-11e8-8dac-31d2e6342031.png)

Fixtures have been applied correctly. IBAN of the account contains whilespaces.

### Observed in (version)
ERPNextSwiss: v0.6.2 (master)

### Steps to reproduce
* Create payments and a bank account to pay from
* Create a payment file

**Comment by lasalesi** [comment]
Detailed debug trace:

	Traceback (most recent call last):
	  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
		response = frappe.handler.handle()
	  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
		data = execute_cmd(cmd)
	  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
		return frappe.call(method, **frappe.form_dict)
	  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
		return fn(*args, **newargs)
	  File "/home/frappe/frappe-bench/apps/erpnextswiss/erpnextswiss/erpnextswiss/page/payment_export/payment_export.py", line 192, in generate_payment_file
		creditor_info = add_creditor_info(payment_record)
	  File "/home/frappe/frappe-bench/apps/erpnextswiss/erpnextswiss/erpnextswiss/page/payment_export/payment_export.py", line 271, in add_creditor_info
		country_code = frappe.get_value('Country', supplier_address.country, 'code').upper()
	AttributeError: 'NoneType' object has no attribute 'upper'

**Comment by lasalesi** [comment]
Country record (desk#List/Country/List) was missing the country code. Added the country code and it works. Also, added a more specific error message (8d15bc4).
