### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by lasalesi** [libracore/erpnextswiss#2]
**Expected behaviour:**
On click on generate payment file the file should be ready for download

**Actual behaviour:**
Error message "TypeError: coercing to Unicode: need string or buffer, NoneType found" is displayed. 
Traceback

    Traceback (most recent call last):
      File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
        response = frappe.handler.handle()
      File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
        data = execute_cmd(cmd)
      File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
        return frappe.call(method, **frappe.form_dict)
      File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
        return fn(*args, **newargs)
      File "/home/frappe/frappe-bench/apps/erpnextswiss/erpnextswiss/erpnextswiss/page/payment_export/payment_export.py", line 53, in generate_payment_file
       content += make_line("        <Nm>" + get_company_name(payments[0]) + "</Nm>")
    TypeError: coercing to Unicode: need string or buffer, NoneType found

**Obeserved in** v0.1 (master)

**Comment by lasalesi** [comment]
Reloading the page resolved the issue. Possibly a problem that the JavaScript passed an empty first option...

**Comment by lasalesi** [comment]
Bugfix implemented in develop. Difficult to explicitly reproduce (negative test)

**Comment by lasalesi** [comment]
Bugfix for JavaScript implemented in v0.3.0
