### ISSUE TITLE
Bank Wizard does not work in Python 3

### ISSUE THREAD

**Issue by lasalesi** [libracore/erpnextswiss#62]
### Expected behvauour
Bank Wizard can be executed

### Actual behaviour
Bank Wiazrd throws an error "unicode is not defined" (Python 3 error):

	Traceback (most recent call last):
	  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
		response = frappe.handler.handle()
	  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
		data = execute_cmd(cmd)
	  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
		return frappe.call(method, **frappe.form_dict)
	  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1026, in call
		return fn(*args, **newargs)
	  File "/home/frappe/frappe-bench/apps/erpnextswiss/erpnextswiss/erpnextswiss/page/bank_wizard/bank_wizard.py", line 194, in read_camt053
		transactions = read_camt_transactions(entries, account)
	  File "/home/frappe/frappe-bench/apps/erpnextswiss/erpnextswiss/erpnextswiss/page/bank_wizard/bank_wizard.py", line 201, in read_camt_transactions
		entry_soup = BeautifulSoup(unicode(entry), 'lxml')
	NameError: name 'unicode' is not defined

### Observed in (version)
v1.4.0

### Steps to reproduce
* Install ERPNext with Python 3
* Run bank wizard

**Comment by lasalesi** [comment]
Resolved in hotfix 8cd837c
