### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'upper' on generation of payment file

### ISSUE THREAD

**Issue by lasalesi** [libracore/erpnextswiss#8]
When trying to create a payment file, the following error occurs

     Traceback (most recent call last):
      File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
        response = frappe.handler.handle()
      File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
        data = execute_cmd(cmd)
      File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
        return frappe.call(method, **frappe.form_dict)
      File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
        return fn(*args, **newargs)
      File "/home/frappe/frappe-bench/apps/erpnextswiss/erpnextswiss/erpnextswiss/page/payment_export/payment_export.py", line 148, in generate_payment_file
        creditor_info = add_creditor_info(payment_record)
      File "/home/frappe/frappe-bench/apps/erpnextswiss/erpnextswiss/erpnextswiss/page/payment_export/payment_export.py", line 268, in add_creditor_info
        country_code = frappe.get_value('Country', supplier_address.country, 'code').upper()
    AttributeError: 'NoneType' object has no attribute 'upper'

It is probably caused by a missing Country setting of a supplier...

**Comment by lasalesi** [comment]
The root cause was that the country definition (see Country list) was customised and the selected country did not contain a country code.

Make sure all used countries have valid country codes.
