### ISSUE TITLE
Unable to uninstall app

### ISSUE THREAD

**Issue by tobiasfeistmantl** [libracore/erpnextswiss#83]
Hello,

when I try to uninstall the app temporarily, it brings up the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tfm/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 99, in <module>
    main()
  File "/home/tfm/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/tfm/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/tfm/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/tfm/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tfm/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tfm/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tfm/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/tfm/frappe-bench/env/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/tfm/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 26, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/tfm/frappe-bench/apps/frappe/frappe/commands/site.py", line 425, in uninstall
    remove_app(app, dry_run, yes)
  File "/home/tfm/frappe-bench/apps/frappe/frappe/installer.py", line 155, in remove_app
    frappe.delete_doc("Module Def", module_name)
  File "/home/tfm/frappe-bench/apps/frappe/frappe/__init__.py", line 795, in delete_doc
    ignore_permissions, flags, ignore_on_trash, ignore_missing)
  File "/home/tfm/frappe-bench/apps/frappe/frappe/model/delete_doc.py", line 101, in delete_doc
    check_if_doc_is_linked(doc)
  File "/home/tfm/frappe-bench/apps/frappe/frappe/model/delete_doc.py", line 244, in check_if_doc_is_linked
    raise_link_exists_exception(doc, linked_doctype, reference_docname)
  File "/home/tfm/frappe-bench/apps/frappe/frappe/model/delete_doc.py", line 299, in raise_link_exists_exception
    .format(doc.doctype, doc_link, reference_doctype, reference_link, row), frappe.LinkExistsError)
  File "/home/tfm/frappe-bench/apps/frappe/frappe/__init__.py", line 376, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable)
  File "/home/tfm/frappe-bench/apps/frappe/frappe/__init__.py", line 355, in msgprint
    _raise_exception()
  File "/home/tfm/frappe-bench/apps/frappe/frappe/__init__.py", line 315, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkExistsError: Cannot delete or cancel because Module Def <a href="#Form/Module Def/ERPNextSwiss">ERPNextSwiss</a> is linked with Print Format <a href="#Form/Print Format/QR Sales Invoice">QR Sales Invoice</a>
```

It looks like the app creates a relation to the DocType "Print Format". However I cannot edit the "Print Format" DocType directly, since it's a core type.

Can you help me on this? I cannot use the app anymore, nor reinstall it.

**Comment by tobiasfeistmantl** [comment]
Found the problem. The app created two print formats, and they were assigned to the erpnextswiss module. Removed them and were able to uninstall app without problems.
