### ISSUE TITLE
uninstall issue

### ISSUE THREAD

**Issue by wojosc** [libracore/erpnextswiss#95]
### Expected behvauour
Uninstall should get rid of everything that was installed

### Actual behaviour
some stuff seems to be left over

### Observed in (version)
<img width="973" alt="grafik" src="https://user-images.githubusercontent.com/22279621/126515231-52761a10-60a9-4cea-a1eb-1080131c99b6.png">

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1172, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/linked_with.py", line 43, in get_submitted_linked_docs
    linked_docs = get_linked_docs(doctype, name, linkinfo)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/linked_with.py", line 168, in get_linked_docs
    link_meta_bundle = frappe.desk.form.load.get_meta_bundle(dt)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 80, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 32, in get_meta
    meta.set_translations(frappe.local.lang)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/meta.py", line 208, in set_translations
    self.set("__messages", frappe.get_lang_dict("doctype", self.name))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 114, in get_lang_dict
    return get_dict(fortype, name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/translate.py", line 103, in get_dict
    messages = get_messages_from_doctype(name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/translate.py", line 371, in get_messages_from_doctype
    doctype_file_path = frappe.get_module_path(meta.module, "doctype", meta.name, meta.name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 955, in get_module_path
    return get_pymodule_path(local.module_app[module] + "." + module, *joins)
KeyError: 'erpnextswiss'
2 request.js:387:14

### Steps to reproduce
not sure

**Comment by lasalesi** [comment]
From the screenshot, this looks like v13, did you use the v13 branch? v13 introduced several breaking changes which prevent normal function...

**Comment by wojosc** [comment]
@lasalesi yes, we are using v13 here. But we had installed it on v12 and uninstalled it on v12. It seems though, that the uninstallation process does not remove all code? As this error is after uninstallation.

Thanks!

**Comment by lasalesi** [comment]
If it was uninstalled in v12 before the upgrade, probably something did not go through as planned.

Can you install ERPNextSwiss - on v13 branch and then remove it again? In case of issues when uninstalling, please revert back with that...

**Comment by lasalesi** [comment]
Probably a bench issue, because indeed it does not remove all code. Ticket at bench is open for a long time (since 2018): https://github.com/frappe/bench/issues/552
